### ISSUE TITLE
Implementar emissao de NFe

### ISSUE THREAD

**Issue by mtrystao** [jheizerwandel/webliniaerp-web#11]

**Comment by filipecoelho** [comment]
Atualização [2016-01-19]:
1 - Trocar todas as referências de código de item de controle para o id do registro (já alinhamos)
2 - Adicionar campo cod_regra_tributos (lista de Regras de Tributos do empreendimento) na tabela tbl_produtos
3 - Adicionar campo num_cest (campo digitável) na tabela tbl_produtos e na tabela tbl_filtro_tributos
4 - Implementar método na FiltroTributosDAO que:
	- Pesquise pelos seguintes parâmetros:
		- id_empreendimento
		- id_cliente
		- id_operacao
		- id_produto
		- nme_tributo
	- Faça o seguinte INNER JOIN, de acordo com o parâmetro nme_tributo
		- Caso seja 'ICMS':
			- INNER JOIN tbl_configuracao_icms ON tbl_configuracao_icms.cod_filtro_tributos = tbl_filtro_tributos.cod_filtro_tributos
		- Caso seja 'PIS_COFINS':
			- INNER JOIN tbl_configuracao_pis_cofins ON tbl_configuracao_pis_cofins.cod_filtro_tributos = tbl_filtro_tributos.cod_filtro_tributos
		- Caso seja 'IPI':
			- INNER JOIN tbl_configuracao_ipi ON tbl_configuracao_ipi.cod_filtro_tributos = tbl_filtro_tributos.cod_filtro_tributos
5 - Terminar de carregar os dados dos itens da NF com as informações do produto

Após totalizar a NF:
7 - Verificar com o Fischer quais informações da NF precisamos armazenar na tabela tb_nota_fiscal, pois ele não mencionou e a tabela não tem nenhum campo atualmente
8 - Percorrer os itens da NF e adicionar na tabela tb_nota_fiscal_item

Urgente:
6 - Adicionar os seguintes campos ao cadastro de fornecedores (Será usado para o cadastro de transportadores, muito importante para a Edna)
	- nme_razao_social (Razão Social)
	- nme_fantasia (Nome Fantasia)
	- num_cnpj (Núm. CNPJ)
	- num_inscricao_estadual (Inscrição Estadual)
	- nme_logradouro (Endereço)
	- num_logradouro (Número)
	- num_cep (CEP)
	- nme_bairro_logradouro (Bairro)
	- cod_estado (Estado)
	- cod_cidade (Cidade)
